# Generated by Django 2.1.7 on 2020-07-26 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200726_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 26, 9, 47, 22, 622144)),
        ),
    ]
